# Generated by Django 2.1.7 on 2019-03-22 13:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appetizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('type', models.IntegerField(choices=[(1, 'sałatka'), (2, 'zupa')])),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('date', models.DateTimeField(default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='Beverages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Lunch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('type', models.IntegerField(choices=[(1, 'mięsny'), (2, 'wegetariański'), (3, 'wegańśki')])),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('date', models.DateTimeField(default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('points', models.IntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime.today)),
                ('appetizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buy_lunch.Appetizer')),
                ('beverage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buy_lunch.Beverages')),
                ('lunch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buy_lunch.Lunch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
