# Generated by Django 2.1.7 on 2019-03-24 12:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buy_lunch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppetizerDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='LunchDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='final_price',
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='points_collected',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='appetizer',
            name='date',
        ),
        migrations.RemoveField(
            model_name='lunch',
            name='date',
        ),
        migrations.AlterField(
            model_name='order',
            name='appetizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buy_lunch.Appetizer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='beverage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buy_lunch.Beverages'),
        ),
        migrations.AlterField(
            model_name='order',
            name='points',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buy_lunch.Points'),
        ),
        migrations.AddField(
            model_name='appetizer',
            name='date',
            field=models.ManyToManyField(to='buy_lunch.AppetizerDate'),
        ),
        migrations.AddField(
            model_name='lunch',
            name='date',
            field=models.ManyToManyField(to='buy_lunch.LunchDate'),
        ),
    ]
