# Generated by Django 2.1.7 on 2019-03-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_lunch', '0002_auto_20190324_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lunch',
            name='date',
        ),
        migrations.AddField(
            model_name='lunchdate',
            name='lunch',
            field=models.ManyToManyField(to='buy_lunch.Lunch'),
        ),
    ]
