# Generated by Django 2.1.7 on 2019-03-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_lunch', '0003_auto_20190324_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appetizer',
            name='date',
        ),
        migrations.AddField(
            model_name='appetizerdate',
            name='appetizer',
            field=models.ManyToManyField(to='buy_lunch.Appetizer'),
        ),
    ]
