# Generated by Django 2.1.7 on 2019-03-31 13:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buy_lunch', '0004_auto_20190324_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.today)),
            ],
        ),
        migrations.AlterField(
            model_name='lunch',
            name='type',
            field=models.IntegerField(choices=[(1, 'mięsny'), (2, 'wegetariański'), (3, 'wegański')]),
        ),
        migrations.AddField(
            model_name='menu',
            name='lunch_meat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lunch_meat', to='buy_lunch.Lunch'),
        ),
        migrations.AddField(
            model_name='menu',
            name='lunch_vegan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lunch_vegan', to='buy_lunch.Lunch'),
        ),
        migrations.AddField(
            model_name='menu',
            name='lunch_vegetarian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lunch_vegetarian', to='buy_lunch.Lunch'),
        ),
        migrations.AddField(
            model_name='menu',
            name='salad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salad', to='buy_lunch.Appetizer'),
        ),
        migrations.AddField(
            model_name='menu',
            name='soup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soup', to='buy_lunch.Appetizer'),
        ),
    ]
