# Generated by Django 2.1.7 on 2019-03-31 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buy_lunch', '0006_auto_20190331_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appetizerdate',
            name='appetizer',
        ),
        migrations.RemoveField(
            model_name='lunchdate',
            name='lunch',
        ),
        migrations.RenameField(
            model_name='appetizer',
            old_name='name',
            new_name='appetizer_name',
        ),
        migrations.RenameField(
            model_name='appetizer',
            old_name='price',
            new_name='appetizer_price',
        ),
        migrations.RenameField(
            model_name='beverages',
            old_name='name',
            new_name='beverage_name',
        ),
        migrations.RenameField(
            model_name='beverages',
            old_name='price',
            new_name='beverage_price',
        ),
        migrations.RenameField(
            model_name='lunch',
            old_name='name',
            new_name='lunch_name',
        ),
        migrations.RenameField(
            model_name='lunch',
            old_name='price',
            new_name='lunch_price',
        ),
        migrations.RenameField(
            model_name='lunch',
            old_name='type',
            new_name='lunch_type',
        ),
        migrations.DeleteModel(
            name='AppetizerDate',
        ),
        migrations.DeleteModel(
            name='LunchDate',
        ),
    ]
