# Generated by Django 2.1.7 on 2019-04-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_lunch', '0009_lunchreview_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lunchreview',
            name='lunch',
        ),
        migrations.AddField(
            model_name='lunchreview',
            name='lunch',
            field=models.ManyToManyField(to='buy_lunch.Lunch'),
        ),
    ]
