# Generated by Django 2.1.7 on 2019-04-22 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_lunch', '0016_menureview_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.today, unique=True),
        ),
    ]
