# Generated by Django 2.1.7 on 2019-04-22 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_lunch', '0017_auto_20190422_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='menu',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.today, error_messages={'unique': 'Lunch na ten dzień już istnieje'}, unique=True),
        ),
    ]
